services:
  redis:
    build:
      dockerfile: redis.Dockerfile
    container_name: redis
    cap_add:
      - NET_ADMIN
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./app
    container_name: worker
    command: uv run celery -A celery_app worker --loglevel=info -Q hello_queue --events
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/1
    depends_on:
      - redis
    mem_limit: 500m

  beat:
    build:
      context: ./app
    container_name: beat
    command: uv run celery -A celery_app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/1
    volumes:
      - ./app:/app
    depends_on:
      - redis

  chaos:
    build:
      context: ./chaos
    container_name: chaos
    ports:
      - "8000:8000"
    volumes:
      - ./chaos:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#     ports:
#       - "9090:9090"

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     ports:
#       - "3000:3000"
#     environment:
#       - GF_SECURITY_ADMIN_USER=admin
#       - GF_SECURITY_ADMIN_PASSWORD=admin
#     volumes:
#       - grafana_data:/var/lib/grafana

#   celery-exporter:
#     image: ovalmoney/celery-exporter
#     container_name: celery-exporter
#     ports:
#       - "9540:9540"
#     environment:
#       - BROKER_URL=redis://redis:6379/0
#     depends_on:
#       - redis

# volumes:
#   grafana_data:
